### ISSUE TITLE
Workshop: Zug September 2023

### ISSUE THREAD

**Issue by ghost** [cspr-rad/logistics#7]
**Dates**

Monday 25th September -> Friday 29th September

**Location**

Seestrasse 5, 6300 Zug, Switzerland

**Attendees**

- https://github.com/NorfairKing
- https://github.com/asladeofgreen
- https://github.com/marijanp
- https://github.com/pinktrink
- https://github.com/jonas089
- https://github.com/CSVdB

**TODO**

- [x] Reserve Seestrasse meeting rooms
- [x] Reserve Zug accommodation
- [x] Confirm attendee travel logistics

**Comment by asladeofgreen** [comment]
**Dates**

Monday 25th September -> Friday 29th September

**Comment by ghost** [comment]
### Agenda

## Introduction

**Schedule:**  

- Breakfast at Hotel Lowen from **08:15** onwards.
- Workshop core hours:  **10:00 - 17:00**.
- Lunch core hours: 12:30 - 13:30.
- Wednesday evening = ACTUS meet-up
- Daily tech video discussion session

## Day One: Monday 25th September

- Internal
  - review logistics board
  - review grants board
  - introduce process as a discussion
- Casper Node deep dive
  - review mind map
  - net | vm | dB | consensus
  - testing

## Day Two: Tuesday 26th September

- Solidity -> Rust Transpiler 
- Exercise Project Review
  - specification
  - implementations
  - next steps
- Lita Foundation Collaboration
  - Valida VM
  - Rollup Infrastructure
  - SDK

## Day Three: Wednesday 27th September

- ACTUS 1
  - Standard
    - overview
    - taxonomy
    - specification
  - Rust Implementation
    - progess
    - blockers
    - next steps

- ACTUS 2
  - ZK-Proofs
    - review of circuit systems
    - review of VMs
    - review of eDSLs
  - DLT Integration
    - why, when, what
    - tokenisation model

- ACTUS 3
  - Gateway
    - platform of platforms
    - customer focus
    - group design process
    
- ACTUS Meetup
  - Zurich @ 18:30
  
## Day Four: Thursday 28th September

- Free coding / design

## Day Five: Friday 29th September

- Free coding / design
- Internal
  - cop28 techsprint
- Workshop Review
  - lessons learnt
  - next steps
  - next workshop date

**Comment by ghost** [comment]
Hotel Invoice for Hotel Lowen

[invoice 23.09.-01.10.2023 Casper Association.pdf](https://github.com/cspr-rad/logistics/files/12782617/invoice.23.09.-01.10.2023.Casper.Association.pdf)



[additional extras - restaurant & laundry receipts.pdf](https://github.com/cspr-rad/logistics/files/12782618/additional.extras.-.restaurant.laundry.receipts.pdf)

**Comment by JHallager** [comment]
Invoice has been settled
